change l2 to sequencer
- make l2 account to use legacyUDC
- change .env.ci.tes
- run boostrapper v1 udc mode on l2 as well

diff --git a/.github/workflows/deploy-bridge.yml b/.github/workflows/deploy-bridge.yml
--- a/.github/workflows/deploy-bridge.yml
+++ b/.github/workflows/deploy-bridge.yml
@@ -50,7 +50,7 @@ jobs:
             --base-path ./madara-l2-db \
             --rpc-external --rpc-admin --rpc-cors "*" \
             --rpc-port 9944 --rpc-admin-port 9943 \
-            --devnet --chain-config-path /apps/configs/presets/devnet.yaml \
+            --sequencer --chain-config-path /apps/configs/presets/devnet.yaml \
             --feeder-gateway-enable --gateway-enable --gateway-external --gateway-port 8844 \
             --no-l1-sync --no-charge-fee \
             --blob-gas-price 0 2>&1 | tee -a ./madara_output_l2.log
@@ -69,6 +69,36 @@ jobs:
             fi
           done
           echo "Server is ready!"
+      
+      - name: Remove l2_deployer_address from devnet.yaml
+        run: |
+          yq -i 'del(.l2_deployer_address)' ./madara/bootstrapper/src/configs/devnet.json
+  
+      - name: Run Bootstrapper on L2
+        run: |
+          docker run -d --name bootstrapper-udc --network bridge-network \
+            -v ./madara/bootstrapper/src/configs/:/apps/configs/ \
+            -e ETH_RPC=http://l2-node:9944 \
+            -e ETH_PRIVATE_KEY=0x077e56c6dc32d40a67f6f7e6625c8dc5e570abe49c0a24e9202e4ae906abcc07 \
+            -e CONFIG_HASH_VERSION=StarknetOsConfig2 \
+            -e ROLLUP_SEQ_URL=http://l3-node:9944 \
+            -e ROLLUP_DECLARE_V0_SEQ_URL=http://l3-node:9943 \
+            -e ROLLUP_PRIVATE_KEY=0xabcd \
+            ghcr.io/madara-alliance/bootstrapper:nightly \
+            --config /apps/configs/devnet.json --mode udc
+
+          # Wait for container to finish
+          EXIT_CODE=$(docker wait bootstrapper-udc)
+
+          # Show logs
+          docker logs bootstrapper-udc
+          
+          # Check exit status
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "Bootstrapper container failed with exit code $EXIT_CODE"
+            exit 1
+          fi
+          echo "Bootstrapper container completed successfully" 
 
       - name: Setup asdf
         uses: asdf-vm/actions/setup@v4
